import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navigation/Navbar";
import { Suspense } from "react";
import QueryProvider from "./components/core/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <Navbar></Navbar>
          <Suspense fallback={<p>Carregando...</p>}>
            {children}
          </Suspense>
        </QueryProvider>
      </body>
    </html>
  );
}
